/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PAvatar: typeof import('primevue/avatar')['default']
    PButton: typeof import('primevue/button')['default']
    PCheckbox: typeof import('primevue/checkbox')['default']
    PColumn: typeof import('primevue/column')['default']
    PDataTable: typeof import('primevue/datatable')['default']
    PDrawer: typeof import('primevue/drawer')['default']
    PForm: typeof import('@primevue/forms/form')['default']
    PIftaLabel: typeof import('primevue/iftalabel')['default']
    PInputGroup: typeof import('primevue/inputgroup')['default']
    PInputText: typeof import('primevue/inputtext')['default']
    PMessage: typeof import('primevue/message')['default']
    PSelect: typeof import('primevue/select')['default']
    PSkeleton: typeof import('primevue/skeleton')['default']
    PToggleButton: typeof import('primevue/togglebutton')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
